# 使うべきでない関数を使用しているかどうかのみ検証
select = ["TID"]

[lint.flake8-tidy-imports.banned-api]
"enum".msg = "Enumを表現したい場合は openfisca_core.indexed_enums.Enum を使用してください。"
"numpy.max".msg = "複数世帯の場合に正しく計算できないため、代わりに 対象世帯.max を使用してください。"
"numpy.min".msg = "複数世帯の場合に正しく計算できないため、代わりに 対象世帯.min を使用してください。"
"numpy.all".msg = "複数世帯の場合に正しく計算できないため、代わりに 対象世帯.all を使用してください。"
"numpy.any".msg = "複数世帯の場合に正しく計算できないため、代わりに 対象世帯.any を使用してください。"
"numpy.sum".msg = "複数世帯の場合に正しく計算できないため、代わりに 対象世帯.sum を使用してください。"
"numpy.argsort".msg = "複数世帯の場合に正しく計算できないため、世帯員を年齢順にしたい場合は 対象世帯.get_rank を使用してください。"
